version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pgdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: product
    ports:
      - "8080:8080"
